name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
:thumbsup:
Haz clic para reaccionar
:pleading_face:
Haz clic para reaccionar
:white_check_mark:
Haz clic para reaccionar
AÃ±adir reacciÃ³n
Responder
Reenviar
MÃ¡s

Enviar mensaje a @Player Marcos
ï»¿
Â¡Mejora a tus amigos! RegÃ¡lales increÃ­bles ventajas de chat con Nitro.
Enviar GIF
Enviar sticker
Ejecutar aplicaciones
Perfil de Player Marcos

MÃ¡s


Player Marcos
AÃ±adir nota (solo es visible para ti)
playermarcos
Modo Streamer habilitado





Current activity
En canal de voz
FemboyKrayonnecPlayer Marcos
ã€ğŸ”‰ã€ğ•²ğ–Šğ–“ğ–Šğ–—ğ–†ğ–‘
en Grupo comunista alineado a las palomas
Establece un estado de canal

Abrir voz
Sobre mÃ­
Sobre mÃ­
En un mundo de ciegos, el tuerto es el rey.
